# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5479bc05b5df3043e2f07cf5057007b157aa73b14c0057e17b378feeadb13741e6a4043d065462df58cbc362b10a1128fb17480de4a77487becba8b438b324aa

test:
  secret_key_base: 4383023e8d888ecbba85bdf19f6d6e6eef44213750b18591d564fe320479a6e141759d2744d4cbf5d1375d3bed2ba342fb748d2c55b975bd61b30ad0cac97539

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
